Đề bài:

1. Dữ liệu đầu vào: một ma trận kích thước $3 \times 3$

2. Mạng nơ ron có kiến trúc lần lượt gồm các lớp:
- Convolution
- Batch Normalization
- ReLU
- MaxPooling
- Fully Connected

Với đầu vào và thông tin chi tiết về mạng nơ rong được mô tả trong hình, hãy trả lời các câu hỏi sau về tính toán giá trị đầu ra sau mỗi lớp của mạng nơ ron trên.


#### Câu 1: Tính toán đầu ra sau lớp Convolution (làm tròn đến 1 chữ số thập phân)

**Đáp án:** A

A.  $ \begin{bmatrix} 3.0 & 3.0 \\ 3.0 & 3.0 \end{bmatrix} \quad \begin{bmatrix} 3.0 & 3.0 \\ 3.0 & 3.0 \end{bmatrix} $

B.  $ \begin{bmatrix} 2.0 & 2.0 \\ 2.0 & 2.0 \end{bmatrix} \quad \begin{bmatrix} 2.0 & 2.0 \\ 2.0 & 2.0 \end{bmatrix} $

C.  $ \begin{bmatrix} 3.0 & 3.0 \\ 3.0 & 3.0 \end{bmatrix} \quad \begin{bmatrix} 6.0 & 3.0 \\ 3.0 & 6.0 \end{bmatrix} $

D.  $ \begin{bmatrix} 2.0 & 2.0 \\ 2.0 & 2.0 \end{bmatrix} \quad \begin{bmatrix} 2.0 & 2.0 \\ 2.0 & 3.0 \end{bmatrix} $



#### Câu 2: Tính toán đầu ra sau lớp Batch Normalization và ReLU (làm tròn đến 1 chữ số thập phân)

**Đáp án:** B

A.  $ \begin{bmatrix} 2.0 & 2.0 \\ 2.0 & 2.0 \end{bmatrix} \quad \begin{bmatrix} 2.0 & 2.0 \\ 2.0 & 2.0 \end{bmatrix} $

B.  $ \begin{bmatrix} 4.0 & 4.0 \\ 4.0 & 4.0 \end{bmatrix} \quad \begin{bmatrix} 4.0 & 4.0 \\ 4.0 & 4.0 \end{bmatrix} $

C.  $ \begin{bmatrix} 0.0 & 0.0 \\ 0.0 & 0.0 \end{bmatrix} \quad \begin{bmatrix} 0.0 & 0.0 \\ 0.0 & 0.0 \end{bmatrix} $

D.  $ \begin{bmatrix} 3.0 & 3.0 \\ 3.0 & 3.0 \end{bmatrix} \quad \begin{bmatrix} 3.0 & 3.0 \\ 3.0 & 3.0 \end{bmatrix} $



#### Câu 3: Tính toán đầu ra sau lớp MaxPooling (làm tròn đến 1 chữ số thập phân)

**Đáp án:** D

A.  $ \begin{bmatrix} 2.0 \end{bmatrix} \quad \begin{bmatrix} 2.0 \end{bmatrix} $

B.  $ \begin{bmatrix} 1.5 \end{bmatrix} \quad \begin{bmatrix} 1.5 \end{bmatrix} $

C.  $ \begin{bmatrix} 3.0 \end{bmatrix} \quad \begin{bmatrix} 3.0 \end{bmatrix} $

D.  $ \begin{bmatrix} 4.0 \end{bmatrix} \quad \begin{bmatrix} 4.0 \end{bmatrix} $



#### Câu 4: Tính toán đầu ra cuối cùng sau lớp Fully Connected (làm tròn đến 1 chữ số thập phân)

**Đáp án:** C

A.  $ \begin{bmatrix} 7.0 \end{bmatrix} $

B.  $ \begin{bmatrix} 8.0 \end{bmatrix} $

C.  $ \begin{bmatrix} 9.0 \end{bmatrix} $

D.  $ \begin{bmatrix} 10.0 \end{bmatrix} $

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np


class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()

        self.conv = nn.Conv2d(in_channels=1, out_channels=2, kernel_size=2)
        self.bn = nn.BatchNorm2d(num_features=2)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.fc = nn.Linear(in_features=2, out_features=1)

    def forward(self, x):
        x = self.conv(x)
        print("After conv:\n", x.detach().cpu().numpy().round(2))
        x = self.bn(x)
        x = F.relu(x)
        print("After BN and ReLU:\n", x.detach().cpu().numpy().round(2))
        x = self.pool(x)
        print("After MaxPooling:\n", x.detach().cpu().numpy().round(2))
        x = x.view(x.size(0), -1)
        x = self.fc(x)
        print("After FC:\n", x.detach().cpu().numpy().round(2))
        return x

In [ ]:
input_tensor = torch.tensor(
    [[[
        [1.0, 1.0, 1.0],
        [1.0, 1.0, 1.0],
        [1.0, 1.0, 1.0]]]]
)
print(f"Input tensor:\n{input_tensor.detach().cpu().numpy().round(2)}")


net = SimpleCNN()
with torch.no_grad():
    net.eval()
    net.conv.weight = nn.Parameter(torch.tensor(
        [[[
            [1.0, 0.0],
            [0.0, 1.0]]],
        [[
            [0.0, 1.0],
            [1.0, 0.0]]]]
    ))
    net.conv.bias = nn.Parameter(torch.tensor([1.0, 1.0]))

    # Batch Norm parameters
    net.bn.weight = nn.Parameter(torch.tensor([1.0, 1.0]))
    net.bn.bias = nn.Parameter(torch.tensor([1.0, 1.0]))
    net.bn.running_mean = torch.tensor([0.0, 0.0])
    net.bn.running_var = torch.tensor([1.0, 1.0])

    net.fc.weight = nn.Parameter(torch.tensor([[1.0, 1.0]]))
    net.fc.bias = nn.Parameter(torch.tensor([1.0]))


output = net(input_tensor)

Input tensor:
[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]]
After conv:
 [[[[3. 3.]
   [3. 3.]]

  [[3. 3.]
   [3. 3.]]]]
After BN and ReLU:
 [[[[4. 4.]
   [4. 4.]]

  [[4. 4.]
   [4. 4.]]]]
After MaxPooling:
 [[[[4.]]

  [[4.]]]]
After FC:
 [[9.]]


### Câu 5.
Cho ma trận đầu vào có kích thước 10x10, áp dụng phép tích chập với kernel 5x5, stride = 2, padding = 1. Tính kích thước của ma trận đầu ra.

A. 3x3

B. 4x4

C. 5x5

D. 6x6

Phân tích:
- Kích thước ma trận đầu vào: 10x10
- Kích thước kernel: 5x5
- Stride: 2
- Padding: 1

Công thức tính kích thước ma trận đầu ra sau phép tích chập:
$$ \text{Output size} = \left\lfloor \frac{\text{Input size} - \text{Kernel size} + 2 \times \text{Padding}}{\text{Stride}} \right\rfloor + 1$$

Thay vào công thức ta có:
$$ \text{Output size} = \left\lfloor \frac{10 - 5 + 2 \times 1}{2} \right\rfloor + 1 = \left\lfloor \frac{7}{2} \right\rfloor + 1 = 3 + 1 = 4$$

Vậy kích thước của ma trận đầu ra là 4x4.

## Mô tả bài toán

Cho một mạng có kiến trúc như hình vẽ trên, gồm 2 nhánh:
   - **Nhánh chính**: Bao gồm 3 lớp convolution, mỗi lớp đều có BatchNorm và ReLU theo sau.
   - **Nhánh Skip Connection:** Nhánh này sử dụng một lớp convolution (có BatchNorm và ReLU theo sau) để giảm kích thước không gian của tensor đầu vào phù hợp với kích thước của tensor đầu ra từ nhánh chính.

**Lưu ý**: Các lớp convolution trong nhánh chính nếu không được nêu rõ trong hình, thì mặc định stride = 1 và padding = 0.


Với đầu vào là tensor có shape `[1, 3, 64, 64]`:

## Câu 6
Cho trước lớp convolution của nhánh skip connection có padding = 1, hãy tính toán số lượng kernel, kernel size và stride thật phù hợp cho lớp convolution này.

A. Số lượng kernel: 3, kernel size: 7x7, stride: 1

B. Số lượng kernel: 32, kernel size: 3x3, stride: 1

C. Số lượng kernel: 32, kernel size: 5x5, stride: 2

D. Số lượng kernel: 3, kernel size: 7x7, stride: 2

Đáp án D

## Câu 7
Kích thước tensor đầu ra cuối cùng của mạng là bao nhiêu?

A. `[1, 3, 64, 64]`

B. `[1, 32, 32, 32]`

C. `[1, 3, 32, 32]`

D. `[1, 3, 29, 29]`

Đáp án D

In [ ]:
import torch
import torch.nn as nn

class ComplexModel(nn.Module):
    def __init__(self):
        super(ComplexModel, self).__init__()
        # Input shape: [batch_size, 3, 64, 64]

        # Main Branch
        self.main_branch = nn.Sequential(
            nn.Conv2d(in_channels=3, out_channels=32, kernel_size=3, stride=1),  # Output: [batch, 32, 62, 62]
            nn.BatchNorm2d(32),
            nn.ReLU(),

            nn.Conv2d(in_channels=32, out_channels=32, kernel_size=3, stride=1),  # Output: [batch, 32, 60, 60]
            nn.BatchNorm2d(32),
            nn.ReLU(),

            nn.Conv2d(in_channels=32, out_channels=3, kernel_size=3, stride=2),  # Output: [batch, 3, 29, 29]
            nn.BatchNorm2d(3),
            nn.ReLU(),
        )
        # Output shape: [batch_size, 3, 29, 29]

        # Projection Shortcut
        self.projection = nn.Sequential(
            nn.Conv2d(in_channels=3, out_channels=3, kernel_size=7, stride=2),  # Output: [batch, 3, 29, 29]
            nn.BatchNorm2d(3),
            nn.ReLU(),
        )

        self.final_relu = nn.ReLU()

    def forward(self, x):
        # Projection Shortcut
        shortcut = self.projection(x)

        # Main Branch
        x = self.main_branch(x)

        # Residual Connection
        x += shortcut
        x = self.final_relu(x)

        return x

# Create a sample input tensor
input_tensor = torch.randn(1, 3, 64, 64)  # [batch_size, channels, height, width]

# Instantiate and test the model
model = ComplexModel()
output = model(input_tensor)

# Print the shape of the output
print("Output shape:", output.shape)


Output shape: torch.Size([1, 3, 29, 29])


## Câu 8
Cơ chế Skip Connection lần đầu tiên được giới thiệu trong kiến trúc mạng nào?

A. VGGNet

B. AlexNet

C. ResNet

D. MobileNet

Đáp án C

## Câu 9
Kiến trúc GoogleNet giới thiệu khái niệm "Inception Module". Điểm khác biệt chính của Inception Module so với các kiến trúc mạng trước đó là gì?

A. Thay thế lớp pooling bằng các lớp convolution 1x1.

B. Tích hợp nhiều kích thước kernel khác nhau trong cùng một module.

C. Giảm số lượng lớp fully connected.

D. Sử dụng depthwise separable convolution.

Đáp án B