In [1]:
import torch
import torch.nn.functional as F

# Input tensor
x = torch.tensor([[3.0]])

# Target labels
y = torch.tensor([0])

# Weights for the first layer
bias1 = torch.tensor([0.0])
weight1 = torch.tensor([[0.8]])

# Weights for the second layer
bias2 = torch.tensor([0.0, 0.0])
weight2 = torch.tensor([[0.3, -0.4]])

# Loss function
loss_fn = torch.nn.CrossEntropyLoss()

# Perform forward pass
for _ in range(1):
    # Compute hidden layer
    hidden = torch.matmul(x, weight1) + bias1
    print(hidden)

    hidden = F.relu(hidden)
    print(hidden)

    # Compute output layer
    output = torch.matmul(hidden, weight2) + bias2
    print(output)

    # Compute loss
    l_value = loss_fn(output, y)
    print(l_value)

tensor([[2.4000]])
tensor([[2.4000]])
tensor([[ 0.7200, -0.9600]])
tensor(0.1709)


In [2]:
nn.Softmax()(output)

NameError: name 'nn' is not defined

In [ ]:
# Compute -log for 0.8429
value = torch.tensor([0.8429])
neg_log_value = -torch.log(value)
print(neg_log_value)


tensor([0.1709])


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# Input tensor
x = torch.tensor([[3.0]])

# Target labels
y = torch.tensor([0])

# Define the model using nn.Linear and nn.ReLU
class SimpleModel(nn.Module):
    def __init__(self):
        super(SimpleModel, self).__init__()        
        self.layer1 = nn.Linear(2, 2)
        self.layer2 = nn.Linear(2, 2)
        self.relu = nn.ReLU()

    def forward(self, x):
        # Hidden layer
        hidden = self.layer1(x)
        print("Hidden layer (before ReLU):\n", hidden)

        hidden = self.relu(hidden)
        print("Hidden layer (after ReLU):\n", hidden)

        # Output layer
        output = self.layer2(hidden)
        print("Output layer (before softmax):\n", output)        

        return output

# Initialize the model
model = SimpleModel()

# Manually set weights and biases
model.layer1.weight.data = torch.tensor([[0.8]])
model.layer1.bias.data = torch.tensor([0.0])
model.layer2.weight.data = torch.tensor([[0.3],
                                         [-0.4]])
model.layer2.bias.data = torch.tensor([0.0, 0.0])

# Loss function
loss_fn = nn.CrossEntropyLoss()

# Perform forward pass and compute loss
output = model(x)
l_value = loss_fn(output, y)
print("Loss:", l_value)

Hidden layer (before ReLU):
 tensor([[2.4000]], grad_fn=<AddmmBackward0>)
Hidden layer (after ReLU):
 tensor([[2.4000]], grad_fn=<ReluBackward0>)
Output layer (before softmax):
 tensor([[ 0.7200, -0.9600]], grad_fn=<AddmmBackward0>)
Loss: tensor(0.1709, grad_fn=<NllLossBackward0>)


In [ ]:
opt = torch.optim.SGD(model.parameters(), lr=0.01)

model.zero_grad()
l_value.backward()
opt.step()

In [ ]:
print(model.layer1.weight)
print(model.layer1.weight.grad)
print(model.layer1.bias)
print(model.layer1.bias.grad)

Parameter containing:
tensor([[0.8033]], requires_grad=True)
tensor([[-0.3299]])
Parameter containing:
tensor([0.0011], requires_grad=True)
tensor([-0.1100])


In [ ]:
print(model.layer2.weight)
print(model.layer2.weight.grad)
print(model.layer2.bias)
print(model.layer2.bias.grad)

Parameter containing:
tensor([[ 0.3038],
        [-0.4038]], requires_grad=True)
tensor([[-0.3770],
        [ 0.3770]])
Parameter containing:
tensor([ 0.0016, -0.0016], requires_grad=True)
tensor([-0.1571,  0.1571])


In [ ]:
-0.157*0.3 - 0.163*0.4

-0.11230000000000001

In [ ]:
0.843-1

-0.15700000000000003

In [ ]:
-0.3299/3

-0.10996666666666667