In [1]:
import torch
import torch.nn.functional as F

# Input tensor
x = torch.tensor([[3.0, 2.0]])

# Target labels
y = torch.tensor([0])

# Weights for the first layer
bias1 = torch.tensor([0.0, 0.0])
weight1 = torch.tensor([[0.8, -1.0],
                        [0.4, -0.6]])

# Weights for the second layer
bias2 = torch.tensor([0.0, 0.0, 0.0])
weight2 = torch.tensor([[0.3,   0.2,  0.1],
                        [-0.4, -1.0,  0.2]])

# Loss function
loss_fn = torch.nn.CrossEntropyLoss()

# Perform forward pass
for _ in range(1):
    # Compute hidden layer
    hidden = torch.matmul(x, weight1) + bias1
    print(hidden.shape, hidden)

    hidden = F.relu(hidden)
    print(hidden.shape, hidden)

    # Compute output layer
    output = torch.matmul(hidden, weight2) + bias2
    print(output.shape, output)

    # Compute loss
    l_value = loss_fn(output, y)
    print(l_value)

torch.Size([1, 2]) tensor([[ 3.2000, -4.2000]])
torch.Size([1, 2]) tensor([[3.2000, 0.0000]])
torch.Size([1, 3]) tensor([[0.9600, 0.6400, 0.3200]])
tensor(0.8125)


In [9]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import random

np.random.seed(0)
random.seed(0)
torch.manual_seed(0)


# Input tensor
x = torch.tensor([[3.0, 2.0]])

# Target labels
y = torch.tensor([0])

# Define the model using nn.Linear and nn.ReLU
class SimpleModel(nn.Module):
    def __init__(self):
        super(SimpleModel, self).__init__()        
        self.layer1 = nn.Linear(2, 2)
        self.layer2 = nn.Linear(2, 3)
        self.relu = nn.ReLU()

    def forward(self, x):
        # Hidden layer
        hidden = self.layer1(x)
        print("Hidden layer (before ReLU):\n", hidden)

        hidden = self.relu(hidden)
        print("Hidden layer (after ReLU):\n", hidden)

        # Output layer
        output = self.layer2(hidden)
        print("Output layer (before softmax):\n", output)

        return output

# Initialize the model
model = SimpleModel()

# Manually set weights and biases
#model.layer1.weight.data = torch.tensor([[0.8, 0.4],
#                                         [-1.0, -0.6]])
#model.layer1.bias.data = torch.tensor([0.0, 0.0])
model.layer2.weight.data = torch.tensor([[0.3, -0.4],
                                         [0.2, -1.0],
                                         [0.1,  0.2]])
model.layer2.bias.data = torch.tensor([0.0, 0.0, 0.0])

# Loss function
loss_fn = nn.CrossEntropyLoss()

# Perform forward pass and compute loss
output = model(x)
l_value = loss_fn(output, y)
print("Loss:", l_value)

Hidden layer (before ReLU):
 tensor([[ 0.4704, -2.5971]], grad_fn=<AddmmBackward0>)
Hidden layer (after ReLU):
 tensor([[0.4704, 0.0000]], grad_fn=<ReluBackward0>)
Output layer (before softmax):
 tensor([[0.1411, 0.0941, 0.0470]], grad_fn=<AddmmBackward0>)
Loss: tensor(1.0523, grad_fn=<NllLossBackward0>)


In [10]:
print(model.layer1.weight)
print(model.layer1.bias)

Parameter containing:
tensor([[ 0.8000,  0.4000],
        [-1.0000, -0.6000]], requires_grad=True)
Parameter containing:
tensor([0., 0.], requires_grad=True)


In [11]:
hidden = model.layer1(x)
print(x)
print(hidden)

tensor([[3., 2.]])
tensor([[ 3.2000, -4.2000]], grad_fn=<AddmmBackward0>)
